version: "3.3"

services:
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      args:
        user: berton
        uid: 1000
      context: ./
      dockerfile: app.Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "33061:3306"
